# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 536)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_logo = QtWidgets.QLabel(self.full_menu_widget)
        self.lb_logo.setMinimumSize(QtCore.QSize(40, 40))
        self.lb_logo.setMaximumSize(QtCore.QSize(40, 40))
        self.lb_logo.setText("")
        self.lb_logo.setPixmap(QtGui.QPixmap(":/icon/icon/question-mark-512.png"))
        self.lb_logo.setScaledContents(True)
        self.lb_logo.setObjectName("lb_logo")
        self.horizontalLayout_2.addWidget(self.lb_logo)
        self.lb_textlogo = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_textlogo.setFont(font)
        self.lb_textlogo.setObjectName("lb_textlogo")
        self.horizontalLayout_2.addWidget(self.lb_textlogo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_home = QtWidgets.QPushButton(self.full_menu_widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(14, 14))
        self.btn_home.setCheckable(True)
        self.btn_home.setAutoExclusive(True)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_2.addWidget(self.btn_home)
        self.btn_camera = QtWidgets.QPushButton(self.full_menu_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_camera.setIcon(icon1)
        self.btn_camera.setIconSize(QtCore.QSize(14, 14))
        self.btn_camera.setCheckable(True)
        self.btn_camera.setAutoExclusive(True)
        self.btn_camera.setObjectName("btn_camera")
        self.verticalLayout_2.addWidget(self.btn_camera)
        self.btn_order = QtWidgets.QPushButton(self.full_menu_widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/activity-feed-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_order.setIcon(icon2)
        self.btn_order.setIconSize(QtCore.QSize(14, 14))
        self.btn_order.setCheckable(True)
        self.btn_order.setAutoExclusive(True)
        self.btn_order.setObjectName("btn_order")
        self.verticalLayout_2.addWidget(self.btn_order)
        self.btn_account = QtWidgets.QPushButton(self.full_menu_widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/group-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/group-512 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_account.setIcon(icon3)
        self.btn_account.setIconSize(QtCore.QSize(14, 14))
        self.btn_account.setCheckable(True)
        self.btn_account.setAutoExclusive(True)
        self.btn_account.setObjectName("btn_account")
        self.verticalLayout_2.addWidget(self.btn_account)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 334, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.full_menu_widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/x-mark-3-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon4)
        self.btn_exit.setIconSize(QtCore.QSize(14, 14))
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_4.addWidget(self.btn_exit)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_search = QtWidgets.QLineEdit(self.widget)
        self.input_search.setObjectName("input_search")
        self.horizontalLayout.addWidget(self.input_search)
        self.btn_search = QtWidgets.QPushButton(self.widget)
        self.btn_search.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/search-3-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon5)
        self.btn_search.setIconSize(QtCore.QSize(14, 14))
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.btn_signin = QtWidgets.QPushButton(self.home_page)
        self.btn_signin.setGeometry(QtCore.QRect(330, 370, 201, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_signin.sizePolicy().hasHeightForWidth())
        self.btn_signin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setKerning(True)
        self.btn_signin.setFont(font)
        self.btn_signin.setStyleSheet("QPushButton#btn_login{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border radius:5px;\n"
"}\n"
"QPushButton#btn_login:pressed{ \n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#btn_login:hover{\n"
" background-color.rgba(2,65, 118, 200);\n"
"}\n"
"")
        self.btn_signin.setObjectName("btn_signin")
        self.lb_password = QtWidgets.QLineEdit(self.home_page)
        self.lb_password.setGeometry(QtCore.QRect(330, 310, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_password.setFont(font)
        self.lb_password.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lb_password.setObjectName("lb_password")
        self.lb_username = QtWidgets.QLineEdit(self.home_page)
        self.lb_username.setGeometry(QtCore.QRect(330, 250, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_username.setFont(font)
        self.lb_username.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px\n"
"")
        self.lb_username.setObjectName("lb_username")
        self.lb_logo_login = QtWidgets.QLabel(self.home_page)
        self.lb_logo_login.setGeometry(QtCore.QRect(330, 20, 201, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_logo_login.sizePolicy().hasHeightForWidth())
        self.lb_logo_login.setSizePolicy(sizePolicy)
        self.lb_logo_login.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lb_logo_login.setText("")
        self.lb_logo_login.setPixmap(QtGui.QPixmap(":/icon/icon/user-512.png"))
        self.lb_logo_login.setScaledContents(True)
        self.lb_logo_login.setObjectName("lb_logo_login")
        self.btn_register = QtWidgets.QPushButton(self.home_page)
        self.btn_register.setGeometry(QtCore.QRect(330, 430, 201, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_register.sizePolicy().hasHeightForWidth())
        self.btn_register.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("QPushButton#btn_login{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border radius:5px;\n"
"}\n"
"QPushButton#btn_login:pressed{ \n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#btn_login:hover{\n"
" background-color.rgba(2,65, 118, 200);\n"
"}\n"
"")
        self.btn_register.setObjectName("btn_register")
        self.stackedWidget.addWidget(self.home_page)
        self.camera_page = QtWidgets.QWidget()
        self.camera_page.setStyleSheet("")
        self.camera_page.setObjectName("camera_page")
        self.layoutWidget = QtWidgets.QWidget(self.camera_page)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 831, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lb_cv2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_cv2.sizePolicy().hasHeightForWidth())
        self.lb_cv2.setSizePolicy(sizePolicy)
        self.lb_cv2.setMinimumSize(QtCore.QSize(539, 349))
        self.lb_cv2.setStyleSheet("\n"
"background-color: rgb(83, 83, 83);")
        self.lb_cv2.setText("")
        self.lb_cv2.setObjectName("lb_cv2")
        self.gridLayout_2.addWidget(self.lb_cv2, 0, 0, 1, 2)
        self.btn_recognition = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_recognition.setObjectName("btn_recognition")
        self.gridLayout_2.addWidget(self.btn_recognition, 2, 1, 1, 1)
        self.btn_get_bill = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_get_bill.setObjectName("btn_get_bill")
        self.gridLayout_2.addWidget(self.btn_get_bill, 2, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout_2.addWidget(self.btn_start, 1, 0, 1, 1)
        self.btn_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout_2.addWidget(self.btn_stop, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.camera_page)
        self.product_page = QtWidgets.QWidget()
        self.product_page.setObjectName("product_page")
        self.table_widget = QtWidgets.QTableWidget(self.product_page)
        self.table_widget.setGeometry(QtCore.QRect(30, 10, 811, 381))
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(3)
        self.table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_widget.setHorizontalHeaderItem(2, item)
        self.layoutWidget1 = QtWidgets.QWidget(self.product_page)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 400, 811, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_search_tb = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_search_tb.setMinimumSize(QtCore.QSize(300, 0))
        self.btn_search_tb.setObjectName("btn_search_tb")
        self.horizontalLayout_3.addWidget(self.btn_search_tb)
        self.edit_search_tb = QtWidgets.QLineEdit(self.layoutWidget1)
        self.edit_search_tb.setObjectName("edit_search_tb")
        self.horizontalLayout_3.addWidget(self.edit_search_tb)
        self.layoutWidget2 = QtWidgets.QWidget(self.product_page)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 440, 811, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_show = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_show.setObjectName("btn_show")
        self.horizontalLayout_5.addWidget(self.btn_show)
        self.btn_cgPrice = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_cgPrice.setObjectName("btn_cgPrice")
        self.horizontalLayout_5.addWidget(self.btn_cgPrice)
        self.btn_insert = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_insert.setObjectName("btn_insert")
        self.horizontalLayout_5.addWidget(self.btn_insert)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_5.addWidget(self.btn_delete)
        self.stackedWidget.addWidget(self.product_page)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.lb_account = QtWidgets.QLabel(self.page_6)
        self.lb_account.setEnabled(True)
        self.lb_account.setGeometry(QtCore.QRect(330, 80, 215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_account.setFont(font)
        self.lb_account.setStyleSheet("")
        self.lb_account.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_account.setObjectName("lb_account")
        self.lb_old_password_c = QtWidgets.QLineEdit(self.page_6)
        self.lb_old_password_c.setGeometry(QtCore.QRect(330, 230, 211, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_old_password_c.setFont(font)
        self.lb_old_password_c.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_old_password_c.setText("")
        self.lb_old_password_c.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lb_old_password_c.setObjectName("lb_old_password_c")
        self.lb_username_c = QtWidgets.QLineEdit(self.page_6)
        self.lb_username_c.setGeometry(QtCore.QRect(330, 150, 211, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_username_c.setFont(font)
        self.lb_username_c.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px\n"
"")
        self.lb_username_c.setObjectName("lb_username_c")
        self.lb_new_password_c = QtWidgets.QLineEdit(self.page_6)
        self.lb_new_password_c.setGeometry(QtCore.QRect(330, 300, 211, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_new_password_c.setFont(font)
        self.lb_new_password_c.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_new_password_c.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lb_new_password_c.setObjectName("lb_new_password_c")
        self.btn_password_c = QtWidgets.QPushButton(self.page_6)
        self.btn_password_c.setGeometry(QtCore.QRect(330, 380, 211, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.btn_password_c.setFont(font)
        self.btn_password_c.setObjectName("btn_password_c")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lb_search = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lb_search.setFont(font)
        self.lb_search.setObjectName("lb_search")
        self.gridLayout_8.addWidget(self.lb_search, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_7)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(330, 70, 201, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lb_username_rg = QtWidgets.QLineEdit(self.page)
        self.lb_username_rg.setGeometry(QtCore.QRect(330, 140, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_username_rg.setFont(font)
        self.lb_username_rg.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_username_rg.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lb_username_rg.setObjectName("lb_username_rg")
        self.lb_password_rg = QtWidgets.QLineEdit(self.page)
        self.lb_password_rg.setGeometry(QtCore.QRect(330, 220, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_password_rg.setFont(font)
        self.lb_password_rg.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_password_rg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lb_password_rg.setObjectName("lb_password_rg")
        self.lb_password_rga = QtWidgets.QLineEdit(self.page)
        self.lb_password_rga.setGeometry(QtCore.QRect(330, 300, 201, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_password_rga.setFont(font)
        self.lb_password_rga.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(48, 82, 101, 255);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px")
        self.lb_password_rga.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lb_password_rga.setObjectName("lb_password_rga")
        self.btn_create = QtWidgets.QPushButton(self.page)
        self.btn_create.setGeometry(QtCore.QRect(330, 380, 201, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create.sizePolicy().hasHeightForWidth())
        self.btn_create.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.btn_create.setFont(font)
        self.btn_create.setStyleSheet("QPushButton#btn_login{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border radius:5px;\n"
"}\n"
"QPushButton#btn_login:pressed{ \n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#btn_login:hover{\n"
" background-color.rgba(2,65, 118, 200);\n"
"}\n"
"")
        self.btn_create.setObjectName("btn_create")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.btn_logout = QtWidgets.QPushButton(self.page_2)
        self.btn_logout.setGeometry(QtCore.QRect(330, 330, 201, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("QPushButton#btn_login{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border radius:5px;\n"
"}\n"
"QPushButton#btn_login:pressed{ \n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#btn_login:hover{\n"
" background-color.rgba(2,65, 118, 200);\n"
"}\n"
"")
        self.btn_logout.setObjectName("btn_logout")
        self.lb_logo_logout = QtWidgets.QLabel(self.page_2)
        self.lb_logo_logout.setGeometry(QtCore.QRect(330, 100, 201, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_logo_logout.sizePolicy().hasHeightForWidth())
        self.lb_logo_logout.setSizePolicy(sizePolicy)
        self.lb_logo_logout.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lb_logo_logout.setText("")
        self.lb_logo_logout.setPixmap(QtGui.QPixmap(":/icon/icon/user-512.png"))
        self.lb_logo_logout.setScaledContents(True)
        self.lb_logo_logout.setObjectName("lb_logo_logout")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.btn_exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_textlogo.setText(_translate("MainWindow", "Cashier"))
        self.btn_home.setText(_translate("MainWindow", " Home"))
        self.btn_camera.setText(_translate("MainWindow", " Camera"))
        self.btn_order.setText(_translate("MainWindow", " Orders"))
        self.btn_account.setText(_translate("MainWindow", " Account"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.input_search.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.btn_signin.setText(_translate("MainWindow", "Sign In"))
        self.lb_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lb_username.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.btn_register.setText(_translate("MainWindow", "Register"))
        self.btn_recognition.setText(_translate("MainWindow", "Recognition"))
        self.btn_get_bill.setText(_translate("MainWindow", "Get bill"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PRODUCT NAME"))
        item = self.table_widget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PRICE"))
        self.btn_search_tb.setText(_translate("MainWindow", "Search"))
        self.edit_search_tb.setPlaceholderText(_translate("MainWindow", "Enter the product name"))
        self.btn_show.setText(_translate("MainWindow", "Show"))
        self.btn_cgPrice.setText(_translate("MainWindow", "Change Price"))
        self.btn_insert.setText(_translate("MainWindow", "INSERT"))
        self.btn_delete.setText(_translate("MainWindow", "DELETE"))
        self.lb_account.setText(_translate("MainWindow", "Change Password"))
        self.lb_old_password_c.setPlaceholderText(_translate("MainWindow", "Old Password"))
        self.lb_username_c.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.lb_new_password_c.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.btn_password_c.setText(_translate("MainWindow", "Done"))
        self.lb_search.setText(_translate("MainWindow", "Search Page"))
        self.label.setText(_translate("MainWindow", "Create Account"))
        self.lb_username_rg.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lb_password_rg.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lb_password_rga.setPlaceholderText(_translate("MainWindow", "Password Again"))
        self.btn_create.setText(_translate("MainWindow", "Done"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
